### PR TITLE
Test venv upgrade with LC_ALL=C

### PR DESCRIPTION
**Pull request by ewilly**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ewilly** [comment]
!gogogadgetoci

**Comment by ewilly** [comment]
!gogogadgetotitus

**Comment by ewilly** [comment]
!gogogadgetotitus

**Comment by ewilly** [comment]
!gogogadgetotitus

**Comment by ewilly** [comment]
idea tested without success => closing

**Comment by tituspijean** [comment]
`dpkg-reconfigure locales` prompts a `dialog` that requires user action, so the installation hangs. We might need to run that with flag to run it without interaction.

**Comment by jedie** [comment]
Nice that @ewilly tries to fix https://github.com/YunoHost/issues/issues/1960 but i think it's not a problem with locales.
It's just because **python3-venv** package is missing. But this should not be the case...

**Pull request closed without merging**
