### PR TITLE
Example

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Don't install on bullseye*
 
## Solution

- *Apply example_ynh*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by jedie** [comment]
That's really a huge diff :(

It really everything needed?!?
Can you split it?

**Comment by jedie** [comment]
can you rebase your PR?

**Comment by yalh76** [comment]
> 
> 
> That's really a huge diff :(
> 
> It really everything needed?!?
> Can you split it?
> 
> Move files into `_dev/` will break things. e.g.: `.editorconfig → _dev/.editorconfig` No editor will recognize this file and ignores it.

I don't know what .editorconfig is for, but usually it's not needed in a YunoHost Package

**Comment by yalh76** [comment]
I don't know what are those pytest but I don't want to manage that

**Pull request closed without merging**
